-- 접속자 확인
SELECT USER FROM DUAL;

DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;
DROP TABLE TITLE;

-- DEPARTMENT 테이블 생성
CREATE TABLE DEPARTMENT (
    DEPT_NO     NUMBER(2),
    DEPT_NAME   VARCHAR2(20),
    FLOOR       NUMBER(2) DEFAULT 2,
    CONSTRAINT  DEPARTMENT_DEPTNO_PK       PRIMARY KEY (DEPT_NO),
    CONSTRAINT  DEPARTMENT_DEPTNAME_UK     UNIQUE(DEPT_NAME),
    CONSTRAINT  DEPARTMENT_DEPTNAME_NN     CHECK(DEPT_NAME IS NOT NULL)
);

-- TITLE 테이블 생성
CREATE TABLE TITLE (
    TITLE_NO   NUMBER(2)    CONSTRAINT TITLE_TITLENO_PK   PRIMARY KEY,
    TITLE_NAME VARCHAR2(10) CONSTRAINT TITLE_TITLENAME_NN NOT NULL CONSTRAINT TITLE_TITLENAME_UK UNIQUE
);

-- EMPLOYEE 테이블 생성
CREATE TABLE EMPLOYEE (
    EMP_NO   NUMBER,
    EMP_NAME VARCHAR2(20) NOT NULL,
    TNO      NUMBER,
    MANAGER  NUMBER,
    SALARY   NUMBER,
    DNO      NUMBER,
    CONSTRAINT EMPLOYEE_EMPNO_PK   PRIMARY KEY (EMP_NO),
    CONSTRAINT EMPLOYEE_TNO_FK     FOREIGN KEY (TNO)     REFERENCES TITLE(TITLE_NO) ON DELETE SET NULL, 
    CONSTRAINT EMPLOYEE_MANAGER_FK FOREIGN KEY (MANAGER) REFERENCES EMPLOYEE(EMP_NO),
    CONSTRAINT EMPLOYEE_SALARY_CK  CHECK (SALARY < 6000000),
    CONSTRAINT EMPLOYEE_DNO_FK     FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DEPT_NO) ON DELETE CASCADE
);

-- 접속한 계정의 테이블 목록 조회
SELECT TABLE_NAME 
  FROM USER_TABLES;
 
-- 접속한 계정의 테이블별 컬럼 조회
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_PRECISION, DATA_LENGTH, NULLABLE, DATA_DEFAULT
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME IN ('EMPLOYEE', 'DEPARTMENT', 'TITLE');

-- 접속한 계정의 테이블별 제약조건 조회
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION, DELETE_RULE
  FROM USER_CONSTRAINTS 
 WHERE TABLE_NAME IN ('EMPLOYEE', 'DEPARTMENT', 'TITLE');
 
 
ALTER TABLE EMPLOYEE ADD hiredate DATE;
SELECT * FROM EMPLOYEE;
UPDATE EMPLOYEE SET hiredate = sysdate;